name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: List files in repository
        run: |
          echo "The repository contains the following files."
          tree
