name: Passing content

on:
  workflow_dispatch:

jobs:
  passing-content:
    runs-on: ubuntu-latest
    steps:
      - id: sets-a-secret
        name: Generate a random secret
        run: |
          the_secret=$(( RANDOM ))
          echo "::add-mask::$the_secret"
          echo "SECRET_NUMBER=$the_secret" >> $GITHUB_OUTPUT
      - name: Use the secret output
        run: |
          echo "The secret is ${{ steps.sets-a-secret.outputs.SECRET_NUMBER }}"
      - name: Define an environment variable
        run: |
          echo "NUM_STEPS=42" >> $GITHUB_ENV
      - name: Show env variable
        run: |
          echo "$NUM_STEPS == ${{ env.NUM_STEPS }}"
          echo "### Summary" >> $GITHUB_STEP_SUMMARY
          echo "This has _worked_." >> $GITHUB_STEP_SUMMARY
      - name: Write Summary from Action
        uses: actions/github-script@v6.1.0
        with:
          script: |
            await core.summary
            .addHeading('Test Results')
            .addTable([
              [{data: 'File', header: true}, {data: 'Result', header: true}],
              ['foo.js', 'Pass ✅'],
              ['bar.js', 'Fail ❌'],
              ['test.js', 'Pass ✅']
            ])
            .addLink('View staging deployment!', 'https://github.com')
            .write()
